standard-labs/real-intent

bigdbm/process/base.py, bigdbm/process/fill.py, bigdbm/process/simple.py, bigdbm/schemas.py, bigdbm/validate/__init__.py, bigdbm/validate/base.py, bigdbm/validate/gender.py, bigdbm/validate/simple.py, pyproject.toml
Use instances of `BaseValidator` subclasses to validate hems, allowing for finer control over processing pipelines and custom profiles.
=> Structure for validators

bigdbm/validate/email.py
Remove any emails that are not deemed 'good' by MillionVerifier.
=> Create an EmailValidator using MillionVerifier

bigdbm/validate/phone.py
Same as EmailValidator but for phone numbers.
=> Validate phone numbers with numverify

bigdbm/client.py
Closes #9.
The `ConnectionError` exception was actually not being handled, because it's raised by `session.send` and is not an HTTP error detailed by the `response.ok` check. 
So this error happens before we check if the response is ok. 
This PR widens the umbrella of errors retried. So now, if a `ConnectionError` occurs, we will wait 10 seconds and retry just like a traditional non-200 code error.
=> Widen umbrella of retried exceptions

bigdbm/validate/pii.py
Only shows people with at least $200k in household income and $250k in household net worth.
=> Create a high net worth validator

bigdbm/analyze/insights/__init__.py
Use an ordered list of insights instead of just a dashed list, so hopefully email clients recognize it...
=> Ordered list of insights

bigdbm/analyze/__init__.py, bigdbm/analyze/insights/__init__.py, bigdbm/analyze/insights/validator_prompt.py, bigdbm/validate/base.py, bigdbm/validate/email.py, bigdbm/validate/home_attrs.py, bigdbm/validate/phone.py, bigdbm/validate/pii.py, bigdbm/validate/simple.py
Create a `ValidatedInsightsGenerator` that takes a `BaseProcessor` object, reads its required and fallback validators, and uses AI to incorporate these into the general understanding of insights. 
Creates a `validation_insight`, a human-readable high-level description of the validation that went into lead generation. Displayed in the final string. 
On validation: These leads have been stripped of unreachable phones and emails, not having repeated entries of the same person, and are ensured to be contactable. These are fine-tuned to a specific location, ensuring the most relevant and actionable dataset possible with strong signals in real estate interests.
1. 68% of leads are associated with the Pre-Movers category, indicating a high potential for engagement with real estate agencies or …
=> Insight generation with validation context

bigdbm/analyze/insights/__init__.py, bigdbm/analyze/insights/validator_prompt.py
=> Improve main validation insight prompt

bigdbm/analyze/insights/__init__.py
The extra was changed from [openai] to [ai].
=> Fix OpenAI import missing error message

pyproject.toml
=> Fix installation parameters

real_intent/deliver/kvcore/__init__.py
=> Optionalize tagging in kvCORE integration

real_intent/deliver/kvcore/__init__.py
Warn isn't a functional attribute it's a parameter in the logger reference.
=> Fix use of internal logging

real_intent/deliver/kvcore/__init__.py, tests/conftest.py, tests/test_followupboss.py, tests/test_kvcore.py
Was previously using an incorrect mechanism of retrieving a lead's email addresses.
=> Fix kvCORE email parsing

real_intent/deliver/followupboss/ai_fields.py
=> Slightly improve OpenAI credentials check

real_intent/client.py
Fixes #91.
Ultimately we just needed to make use of internal functionality already built for this.
=> Proper log spanning of `check_numbers`

real_intent/validate/pii.py
Remove leads below $30k in income. No opinion on Net Worth.
=> Create a MidIncomeValidator

real_intent/deliver/kvcore/__init__.py
Suppress the warning log temporarily.
=> Only trace (not warn) kvCORE DNC log

real_intent/client.py, tests/test_client.py
=> Remove IP enhancement functionality

real_intent/validate/dns.py
Maintain internal cache of emails vs. submissions, as a `set`.
=> Optimize Fillout DNS calculations

real_intent/deliver/followupboss/vanilla.py
Specify source of rate limit in logger message.
=> Improve FUB rate limit log

real_intent/schemas.py, tests/conftest.py, tests/test_analyze.py, tests/test_followupboss.py, tests/test_format.py, tests/test_pii_fake.py, tests/test_validation.py
Automatic faking in one place as a classmethod on the `PII` object itself. Replace all tests.
=> Replace all manual faking with PII classmethod faking

pyproject.toml, requirements.txt
Upgrade to latest versions in the devcontainer, and peg the package's dependencies to the latest OpenAI and Logfire versions.
=> Upgrade dependencies

real_intent/schemas.py
3 emails and 2 phones with random flip for DNC presence.
=> Generate multiple emails and phones in fake PII creation

real_intent/validate/phone.py
Raise the specific error, being the last failure on phone validation, so it's properly sent to a calling function.
=> Propagate any phone validation errors

pyproject.toml
=> Require Anthropic

real_intent/validate/home_attrs.py
Write a `HomeownerValidator` who asserts the object's PII home owner status flag is `"Home Owner"`. Leads must be homeowners.
=> Create a homeowner assertion validator

pyproject.toml
Major version release due to new intent API interface and major processing benefits. And, completely restructured internal routing of IAB categories for payload creation.
=> Bump version v4.0.0

pyproject.toml
Fix project metadata information and bump minimum logfire version for the `[logfire]` extension to at least v3.0.0.
=> Update project metadata and bump logfire

real_intent/validate/phone.py
Previously, post retry mechanism, failures are logged and raised. Adds `raise_on_error: bool = True` to the `PhoneValidator` initializer, manually overridable, to allow processing during bad API times.
=> Add param to proceed without raise on bad phone validation
