bigdbm/validate/simple.py

Create a validator that removes hems that are in a given list of MD5s. 
Useful when ensuring uniqueness in hems between jobs, as you can pass in:
```python
FillProcessor(client).add_validator(MD5Validator(previous_hems)).process(job)
```
And still use the `FillProcessor` to shoot for the correct number of unique leads.

MD5 validator

---

bigdbm/process/base.py
tests/test_processing.py

Allows finer control over the validation order. 
Say `ContactableValidator` is being used along with `EmailValidator`. If contactable runs first, and then email validator removes emails such that a user is no longer contactable, contactable validator has semantically failed. EmailValidator should run first. But if the default validators are automatically injected into the processor object on instantiation, there's no control over which validator runs first.

Insert default validators as a method

---

bigdbm/schemas.py

That way, jobs can be created without needing to explicitly pass in a bunch of empty lists.

Make IABJob parameters optional

---

bigdbm/validate/phone.py

Only show hems where there's at least one phone number. 
If validating phone numbers as well, use this after `PhoneValidator` to ensure no empty phone lists.

Validator for having a phone

---

bigdbm/validate/simple.py

`SamePersonValidator.validate` should be returning a `list[MD5WithPII]` not a `dict[str, MD5WithPII]` as is used within the detection algorithm.

Proper schema for same person detection

---

.gitignore
bigdbm/analyze/__init__.py
bigdbm/analyze/base.py
bigdbm/analyze/insights/__init__.py
bigdbm/analyze/insights/prompt.py
pyproject.toml
requirements.txt

Generate AI insights on a `list[MD5WithPII]`. Utilize OpenAI's new structured `json_schema` mode on the latest GPT-4o snapshot.
Creates an `analyze` structure used outside of the main processing pipeline. `BaseAnalyzer.analyze` method takes a list of PII leads and returns a string. 
`OpenAIInsightsGenerator` is implemented. 
```python
result: list[MD5WithPII] = processor.process(...)
from bigdbm.analyze import OpenAIInsightsGenerator
insights: str = OpenAIInsightsGenerator(openai_api_key=...).analyze(result)
```
Note that there's no in-built logging here as this generator doesn't requrie the BigDBM client. This is the same problem as with the formatters (to be known as deliverers) and validators. Log externally, i.e. from the user code.

AI insights on leads

---

bigdbm/analyze/insights/__init__.py
bigdbm/analyze/insights/validator_prompt.py

This pull request addresses the inconsistency in the insights format between the ValidatedLeadInsights class and the SYSTEM_PROMPT.
Changes made:
1. Updated the description of the insights field in the ValidatedLeadInsights class to specify that each insight should be a complete, self-contained statement without any leading numbers or bullet points.
2. Modified the process_insights method to remove the code that strips leading '- ' characters, as they should no longer be present in the input.
3. Changed the example insights in the SYSTEM_PROMPT from a bullet-point list to a JSON-like array of strings.
4. Added a reminder at the end of the SYSTEM_PROMPT that each insight should be a complete, self-contained statement without any leading numbers or bullet points.
These changes ensure …

Fix insights format inconsistency

---

bigdbm/process/fill.py

Fixes #52
This PR adds a deprecation warning to the NoFallbackFillProcessor class in bigdbm/process/fill.py.
Key changes:
- Import warnings module
- Add deprecation warning to NoFallbackFillProcessor.__init__
- Use DeprecationWarning category
- Set stacklevel=2 for accurate warning location
- Provide clear message recommending FillProcessor
This change maintains backward compatibility while encouraging the use of the FillProcessor class.

Add deprecation warning to NoFallbackFillProcessor

---

real_intent/deliver/csv.py

Use function-locally scoped shallow copy of instance's output columns to ensure the instance is reusable.

Ensure formatter object is reusable

---

real_intent/deliver/csv.py

Previously, the MD5 came first in the PII object, now it's last in the column orders.

Fix sentence order in CSV output

---

real_intent/deliver/kvcore/__init__.py
tests/test_kvcore.py

Closes #94.
Populate kvCORE user's `Agent Notes` (for each lead) with stringified key values of curated PII attributes.
Curated PII attrs are hardcoded. Uses new `._agent_notes` method to allow the entire class to be subclasses for eventual per-lead insights.
Eventually, call `super()._agent_notes(...)` before appending AI insight to the end, similar to the subclassing behavior from the original FUB integration to the AI one.

Agent notes in kvCORE integration

---

real_intent/deliver/followupboss/ai_fields.py
real_intent/deliver/followupboss/vanilla.py

Creation of `@fub_rate_limited` decorator. Applied to any FUB methods interacting with the API. Max retries hardcoded to 5, but intelligently determines the amount of time to wait according to received headers. Also, drop FUB concurrency from 5 to 3.

Proper handling of the FUB rate limit

---

real_intent/deliver/followupboss/vanilla.py

Was still having issues with FUB concurrency. Dropped concurrency and fixed an issue causing the rate limiter not to be used on 429 errors. I think FUB has a special rate limit condition for notes...

Safer FUB concurrency

---

real_intent/deliver/kvcore/__init__.py

Edge case handled where a lead has valid non-DNC phones but does not have any valid emails.

Fix email template formatting in kvCORE integration

---

real_intent/validate/dns.py

Saw 429 client errors caused by the DNS validation process. Maintain an internal, instance-specific cache of submissions updated on initialization. 
No changes to functionality/implementations for dependent code. Does add a new `._update_submissions_cache()` method.

Cache Fillout submissions

---

real_intent/deliver/kvcore/__init__.py
tests/test_kvcore.py

Not much else to say.
With all components present it would format like:
"123 Main St, Springfield, IL, 12345-6789"
And with some components missing it adapts appropriately, e.g.:
"Springfield, IL, 12345"

Physical address in kvCORE agent notes

---

real_intent/validate/email.py

Reverse emails to hash; retroactively remove emails not matching the direct event of intent. Accessible as `RelevantEmailValidator`.

Validator to remove irrelevant emails

---

tests/test_events_generator.py

Asserting the presence of "Chicago" in the summary was a bit of a crapshoot. Remove for more reliability and improve messages in prior assertions.

More reliable event generator test

---

real_intent/deliver/followupboss/__init__.py
real_intent/deliver/followupboss/ai_fields.py
real_intent/deliver/followupboss/vanilla.py
tests/test_followupboss.py

- Rename InvalidAPICredentialsError to InvalidFUBCredentialsError for better clarity
- Add dedicated InvalidOpenAICredentialsError class for OpenAI authentication failures
- Update imports and error handling code to use new error classes
- Expose both deliverers (FollowUpBossDeliverer, AIFollowUpBossDeliverer) and all error classes (InvalidFUBCredentialsError, InvalidOpenAICredentialsError, AccountInactiveError) directly from real_intent.deliver.followupboss package

Improve error handling for Follow Up Boss integration

---

real_intent/client.py

Was cluttering the log space severely, especially for Webhawk with 9 concurrent workers and multiple live instances.

Don't log trace access token updated

---

real_intent/deliver/zapier/__init__.py
tests/test_zapier.py

Instead of `str(key): value`, do `str(key): value if value is not None else None` to include empty values as `None` not `"None"`.

Zapier: Don't stringify nonexistent values

---

real_intent/schemas.py

Closes #188. 
Ensure the format is `%m/%d/%Y` same as live data. Previously the mock data was giving just `%m/%Y`.

Standardize mock PII birthday format

---

real_intent/events/scrapy_claude/__init__.py

One incorrect use, passing `_exc_info` instead of `exc_info`.

Fix the use of exc_info in logs

---

real_intent/validate/pii.py

Introduces a `UHNWValidator` under `real_intent.validate.pii` as a `BaseValidator` type capable of filtering `MD5WithPII` types to only retain profiles with over $250k income and over $499,999 in net worth (the highest possible criterion for each metric).

Implement ultra high net worth validation spec

---

pyproject.toml

Bump version yet one higher as forgot to explicitly bump for v4.6.4 or v4.6.3. This will allow for clean upgrade installs including both those changes at v4.6.5.

Bump version v4.6.5
